---
- name: etl-organization-stats
  hosts: etl-organization-stats
  user: vagrant
  sudo: true
  sudo_user: root

  vars:
    app_user: "vagrant"
    project: "etl-organization-stats"
    project_home: "/var/lib/{{ project }}"
    run_command: "java -jar {{project_home}}/{{ project }}.jar"

  roles:
   - { role: scala-app }
